





connect_debug_port u_ila_0/probe9 [get_nets [list debug_clock]]
connect_debug_port dbg_hub/clk [get_nets debug_clock]

set_property PACKAGE_PIN V24 [get_ports PHY_RXD0]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_RXD0]
set_property PACKAGE_PIN W25 [get_ports PHY_RXD1]
set_property PACKAGE_PIN Y25 [get_ports PHY_RXD4]
set_property PACKAGE_PIN Y28 [get_ports PHY_RXD3]
set_property PACKAGE_PIN AA25 [get_ports PHY_RXD5]
set_property PACKAGE_PIN AA24 [get_ports PHY_RXD6]
set_property PACKAGE_PIN AB25 [get_ports PHY_RXD7]
set_property PACKAGE_PIN W24 [get_ports PHY_RXD2]
set_property PACKAGE_PIN W28 [get_ports PHY_TXD0]
set_property PACKAGE_PIN Y32 [get_ports PHY_TXD2]
set_property PACKAGE_PIN AA28 [get_ports PHY_TXD3]
set_property PACKAGE_PIN AA27 [get_ports PHY_TXD4]
set_property PACKAGE_PIN AB27 [get_ports PHY_TXD5]
set_property PACKAGE_PIN AB26 [get_ports PHY_TXD6]
set_property PACKAGE_PIN AC31 [get_ports PHY_TXD7]
set_property PACKAGE_PIN W26 [get_ports PHY_TXD1]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_RXD1]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_RXD2]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_RXD3]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_RXD4]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_RXD5]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_RXD6]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_RXD7]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_TXD0]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_TXD1]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_TXD2]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_TXD3]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_TXD4]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_TXD5]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_TXD6]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_TXD7]
set_property PACKAGE_PIN Y33 [get_ports PHY_RESET]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_RESET]
set_property PACKAGE_PIN Y30 [get_ports PHY_RXCLK]
set_property PACKAGE_PIN V31 [get_ports PHY_RXCTL_RXDV]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_RXCLK]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_RXCTL_RXDV]
set_property PACKAGE_PIN Y31 [get_ports PHY_TXC_GTXCLK]
set_property PACKAGE_PIN V33 [get_ports PHY_TXER]
set_property PACKAGE_PIN AC33 [get_ports USER_CLK2]
set_property PACKAGE_PIN AC34 [get_ports USER_CLK2_SDA]
set_property PACKAGE_PIN AC29 [get_ports USER_CLK2_SCL]
set_property PACKAGE_PIN V32 [get_ports PHY_TXCTL_TXEN]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_TXC_GTXCLK]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_TXCTL_TXEN]
set_property IOSTANDARD LVCMOS33 [get_ports PHY_TXER]
set_property IOSTANDARD LVCMOS33 [get_ports USER_CLK2]
set_property IOSTANDARD LVCMOS33 [get_ports USER_CLK2_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports USER_CLK2_SDA]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 6 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list debug_pll_inst/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {debug_counter1_sig[0]} {debug_counter1_sig[1]} {debug_counter1_sig[2]} {debug_counter1_sig[3]} {debug_counter1_sig[4]} {debug_counter1_sig[5]} {debug_counter1_sig[6]} {debug_counter1_sig[7]} {debug_counter1_sig[8]} {debug_counter1_sig[9]} {debug_counter1_sig[10]} {debug_counter1_sig[11]} {debug_counter1_sig[12]} {debug_counter1_sig[13]} {debug_counter1_sig[14]} {debug_counter1_sig[15]} {debug_counter1_sig[16]} {debug_counter1_sig[17]} {debug_counter1_sig[18]} {debug_counter1_sig[19]} {debug_counter1_sig[20]} {debug_counter1_sig[21]} {debug_counter1_sig[22]} {debug_counter1_sig[23]} {debug_counter1_sig[24]} {debug_counter1_sig[25]} {debug_counter1_sig[26]} {debug_counter1_sig[27]} {debug_counter1_sig[28]} {debug_counter1_sig[29]} {debug_counter1_sig[30]} {debug_counter1_sig[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {clk0_counter[0]} {clk0_counter[1]} {clk0_counter[2]} {clk0_counter[3]} {clk0_counter[4]} {clk0_counter[5]} {clk0_counter[6]} {clk0_counter[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {LEDD[0]} {LEDD[1]} {LEDD[2]} {LEDD[3]} {LEDD[4]} {LEDD[5]} {LEDD[6]} {LEDD[7]} {LEDD[8]} {LEDD[9]} {LEDD[10]} {LEDD[11]} {LEDD[12]} {LEDD[13]} {LEDD[14]} {LEDD[15]} {LEDD[16]} {LEDD[17]} {LEDD[18]} {LEDD[19]} {LEDD[20]} {LEDD[21]} {LEDD[22]} {LEDD[23]} {LEDD[24]} {LEDD[25]} {LEDD[26]} {LEDD[27]} {LEDD[28]} {LEDD[29]} {LEDD[30]} {LEDD[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {debug_counter2_sig[0]} {debug_counter2_sig[1]} {debug_counter2_sig[2]} {debug_counter2_sig[3]} {debug_counter2_sig[4]} {debug_counter2_sig[5]} {debug_counter2_sig[6]} {debug_counter2_sig[7]} {debug_counter2_sig[8]} {debug_counter2_sig[9]} {debug_counter2_sig[10]} {debug_counter2_sig[11]} {debug_counter2_sig[12]} {debug_counter2_sig[13]} {debug_counter2_sig[14]} {debug_counter2_sig[15]} {debug_counter2_sig[16]} {debug_counter2_sig[17]} {debug_counter2_sig[18]} {debug_counter2_sig[19]} {debug_counter2_sig[20]} {debug_counter2_sig[21]} {debug_counter2_sig[22]} {debug_counter2_sig[23]} {debug_counter2_sig[24]} {debug_counter2_sig[25]} {debug_counter2_sig[26]} {debug_counter2_sig[27]} {debug_counter2_sig[28]} {debug_counter2_sig[29]} {debug_counter2_sig[30]} {debug_counter2_sig[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 4 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {clk0_unlock_counter[0]} {clk0_unlock_counter[1]} {clk0_unlock_counter[2]} {clk0_unlock_counter[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list clk0_locked]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list clk0_stopped]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list clk_in]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list debug_pll_inst/clk_in1]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list debug_locked]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list gen_dtc_clock]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list trig_in]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list USER_CLK1_IBUF]]
set_property PACKAGE_PIN AB24 [get_ports PHY_RXER]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets gen_dtc_clock]
